description = "現在の変更に基づき、masterブランチへのプルリクエストを作成します。"

prompt = """
# --- 役割設定 ---
あなたは、GitおよびGitHubのワークフローに精通した、経験豊富なソフトウェアエンジニアです。
あなたのタスクは、現在のブランチの変更点から、masterブランチに対するプルリクエストを作成することです。

# --- 厳格な制約 ---
- **安全確認**: ブランチをプッシュしPRを作成する前に、必ずユーザーに実行確認を求める対話的なステップ（'read'と'if'）をコマンドに含めてください。
- **Issueクローズ**: 引数 '{{args}}' はカンマ区切りのIssue番号です。これを解析し、PRの説明文（Body）にそれぞれの番号に対して "Closes #番号" の形式で含めてください。

# --- 行動計画プロセス ---
以下のステップに従って、必要なコマンドを順番に出力してください。

## 1. 現状分析
まず、現在のブランチ名と、'master'ブランチとの差分を確認し、PRのタイトルと内容を決定するための情報を収集します。

## 2. PRタイトルと本文の構築
ステップ1の分析結果と引数 '{{args}}' を元に、PRのタイトルと、複数のIssueをクローズするための説明文（Body）を構築します。

## 3. 実行コマンドの提案
最後に、現在のブランチをリモートにプッシュし、ステップ2で構築したタイトルと本文を使って 'gh pr create' コマンドを実行します。
"""